version: '3.1'
volumes:
  db-volume:
  ghost-volume:
services:
  db:
    image: mysql:5.7
    container_name: db
    restart: always
    volumes:
      - db-volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ArcherVanderWaal
      MYSQL_DATABASE: blog
      MYSQL_USER: blog-user
      MYSQL_PASSWORD: ArcherVanderWaal
  ghost:
    build: ./ghost
    image: archervanderwaal/ghost:2.15
    container_name: ghost
    volumes:
      - ghost-volume:/var/lib/ghost
    restart: always
    ports:
      - 52057:2368
    environment:
      database__connection__host: db
      database__connection__user: blog-user
      database__connection__password: ArcherVanderWaal
      database__connection__database: blog
    depends_on:
      - db
    entrypoint: ["wait-for-connect.sh", "db", "--", "docker-entrypoint.sh"]
    command: ["node", "current/index.js"]